<?php

namespace FOND\UserBundle\Repository;

/**
 * formulaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class formulaireRepository extends \Doctrine\ORM\EntityRepository
{
}
